#!/bin/sh

set -e

cd "$HOME"

open_term() {
    cd "$dir" && i3-sensible-terminal -e tnew
}

breadthw -t d -s | rofi -dmenu -p 'tmux: ' -matching fuzzy | (read -r dir && [ "$dir" ] && open_term "$dir")
