#!/bin/sh

set -e

cd "$HOME"

dir=$(breadthw -t d -s | rofi -dmenu -p 'tmux: ' -matching fuzzy)

[ "$dir" ] && cd "$dir"

SANE_PWD="$(basename "$PWD" | tr . _)"

exec i3-sensible-terminal -e tmux new-session -As "$SANE_PWD"
